name: Build and Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Set up Node.js to install Firebase CLI
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install Firebase CLI
      - run: npm install -g firebase-tools

      # Authenticate with Firebase using service account JSON
      - name: Firebase Auth
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > "${HOME}/firebase-service-account.json"
          firebase login:ci --token "$(cat ${HOME}/firebase-service-account.json)" || true
          firebase use --add
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      # Build and deploy using Firebase CLI
      - name: Deploy to Firebase Hosting
        run: |
          firebase deploy --only hosting --project assetivo
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
